#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$GLOBALS['ROOT_DIR'] = __DIR__;

use App\Server\Logs\ErrorLog;
use App\Server\Server;
use App\Server\Request;
use App\Server\Response;

$callback = function (Request $request): Response {
    $method = $request->getMethodString();
    $path = $request->getUriString();
    $body = $request->getBodyString();
    $params = $request->getParametersArray();

    return new Response(
        [
            'Server' => 'PHP CLI Server',
            'Content-Type' => 'text/plain',
        ],
        "Method: $method\nPath: $path\nBody: $body \nParams: " . json_encode($params),
        200
    );
};

if (isset($argv[1])) {
    if (str_contains($argv[1], ':')) {
        list($host, $port) = explode(':', $argv[1]);
    } else {
        $host = $argv[1];
        $port = 8080;
    }
} else {
    $host = '127.0.0.1';
    $port = 8080;
}

try {
    $Server = new Server($host, $port);

    $Server->run($callback);
} catch (Exception $e) {
    $message = $e->getMessage();
    $ErrorLog = new ErrorLog();
    $ErrorLog->insertLog(null, $message);
}
